version: "3.9"

services:
  server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.server 
    ports:
      - "4433:4433/tcp"
      - "4433:4433/udp"
      - "4433:4433"
    container_name: nimble-server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"  
    depends_on:
      - server
    container_name: nimble-client
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - client
      - server
    container_name: nginx

  turnserver:
    image: instrumentisto/coturn
    container_name: coturn
    platform: linux/amd64
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "60000-60100:60000-60100/udp" 
    command: >
      -n
      --user user:pass
      --realm myrealm
      --min-port=60000
      --max-port=60100
      --external-ip=192.168.0.111
      --log-file=stdout