FROM --platform=linux/arm64 node:20-alpine

WORKDIR /app

COPY . .

ENV PYTHONUNBUFFERED=1 

RUN rm -rf node_modules package-lock.json \
 && npm install --legacy-peer-deps \
 && npm run build \
 && npm install -g serve

COPY nginx.conf /etc/nginx/nginx.conf
COPY certificate.pem /app/certificate.pem
COPY certificate.key /app/certificate.key

CMD ["sh", "-c", "sleep 5 && serve -s dist -l 5173"]